### ISSUE TITLE
Can coralmaster look for local coralslaveproviders only?

### ISSUE THREAD

**Issue by mrindar** [viproma/coral#20]
An interesting thing just happened; As I was working on some simulations with coral I got a message from a colleague saying that he was unable to start his simulation with coralmaster because it found several FMUs with the same name. 

Apparently, coralmaster finds all coralslaveproviders running on our internal network when it is executed with default parameters as shown below:
```
coralslaveprovider /path/to/fmus -o out/
coralmaster run .execonf .sysconf --name="MySimulation"
```
Is there a way to tell coralmaster to only look for slaveproviders locally? If so, maybe that should be the default?

**Comment by kyllingstad** [comment]
> Is there a way to tell coralmaster to only look for slaveproviders locally?

Yes, and you can also tell coralslaveprovider to only offer its slaves locally. Both take a command line parameter called `--interface`, with which you can select the network interface to use. To only use the local (loopback) interface, specify `--interface=127.0.0.1`. Run `coralmaster run` or `coralslaveprovider` without any arguments to see a help message that gives some more information.

> If so, maybe that should be the default?

Maybe. :-) I'll have to think a bit about that.

**Comment by kyllingstad** [comment]
The "enhancement" label I just added refers to the suggestion of making localhost the default interface.

**Comment by kyllingstad** [comment]
I've had reports from others with the same problem, so I decided to change the default interface to 127.0.0.1. Pull request #31 addresses this.
