### ISSUE TITLE
Assertion failed in coral 0.7

### ISSUE THREAD

**Issue by mrindar** [viproma/coral#33]
From time to time a coralslave crashes with the following message in coral 0.7:
``
Assertion failed: nbytes == sizeof (dummy) (C:\Users\larky\Development\viproma\coral-super\releases\temp\coral_0.7.0_win32-msvc12-release\zmq-prefix\src\zmq\src\signaler.cpp:182)
``
what does this mean?

**Comment by kyllingstad** [comment]
It's very hard to tell without a stack trace. I've googled the error message, and in most cases it seems to happen when people try to use a single ZeroMQ socket from several threads at once. I cannot think of anywhere in Coral where that could happen, though.

Do you have an estimate of how often this happens, and under which circumstances? Windows or Linux?

**Comment by mrindar** [comment]
I have only seen this under windows (don't really run a lot of simulation under linux at the moment), and it happens very rarely, like 1 in 50, maybe even less.

**Comment by kyllingstad** [comment]
This appears to be a ZeroMQ issue, described here: https://github.com/zeromq/libzmq/issues/2303
And fixed here: https://github.com/zeromq/libzmq/pull/2360
The solution is to update to ZeroMQ 4.2 or greater.
